spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/carts_repository
    username:
    password:
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: validate
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

    flyway:
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}

application:
    product-service:
      url: http://localhost:8222/api/v1/products

    user-service:
      url: http://localhost:8222/api/v1/users

    ingredient-service:
      url: http://localhost:8222/api/v1/ingredients

server:
  port: 8030
