spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/carts_repository
    username:
    password:
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: validate
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

    flyway:
      url: ${spring.datasource.url}
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}

springdoc:
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8030
