spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: product-service-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**

        - id: ingredients-service-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/ingredients/**

        - id: product-items-service-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product-items/**

        - id: categories-service-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/categories/**

        - id: dough-type-service-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/dough-types/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods: GET, POST, DELETE, PUT, OPTIONS

server:
  port: 8222
