spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**

        - id: ingredients-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/ingredients/**

        - id: product-items-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product-items/**

        - id: categories-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/categories/**

        - id: dough-type-service-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/dough-types/**

server:
  port: 8222
