spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/products_repository
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

logging:
  level:
    root: info

springdoc:
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8020
