spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/next-pizza
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8010
