-- Keycloak
CREATE DATABASE $${KEYCLOAK_DB_NAME};
CREATE USER $${POSTGRES_USER} WITH PASSWORD '$${POSTGRES_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE $${KEYCLOAK_DB_NAME} TO $${POSTGRES_USER};
ALTER DATABASE $${KEYCLOAK_DB_NAME} OWNER TO $${POSTGRES_USER};

-- Product-service
CREATE DATABASE $${PRODUCT_SERVICE_DB_NAME};
CREATE USER $${POSTGRES_USER} WITH PASSWORD '$${POSTGRES_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE $${PRODUCT_SERVICE_DB_NAME} TO $${POSTGRES_USER};
ALTER DATABASE $${PRODUCT_SERVICE_DB_NAME} OWNER TO $${POSTGRES_USER};

-- User-service
CREATE DATABASE $${USER_SERVICE_DB_NAME};
CREATE USER $${POSTGRES_USER} WITH PASSWORD '$${POSTGRES_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE $${USER_SERVICE_DB_NAME} TO $${POSTGRES_USER};
ALTER DATABASE $${USER_SERVICE_DB_NAME} OWNER TO $${POSTGRES_USER};

-- Cart-service
CREATE DATABASE $${CART_SERVICE_DB_NAME};
CREATE USER $${POSTGRES_USER} WITH PASSWORD '$${POSTGRES_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE $${CART_SERVICE_DB_NAME} TO $${POSTGRES_USER};
ALTER DATABASE $${CART_SERVICE_DB_NAME} OWNER TO $${POSTGRES_USER};
